header_pages:
  - index.md
  - about.md

footer: '
  Know more about me on <a href="https://zemin-xu.github.com/">Github</a><&nbsp>
        '

style: dark # dark (default) or light
listen_for_clients_preferred_style: false # true or false (default)

plugins:
  - jekyll-seo-tag
